const baseline = [
  {id:5016,btc:[18,27.8,.07,1.09],eth:[11,36.4,.42,1.66],rules:[60,.75,50,30,100,.10,3]},
  {id:4970,btc:[33,27.3,.06,1.08],eth:[24,37.5,.46,1.73],rules:[60,.75,30,30,0,.50,3]},
  {id:3350,btc:[23,26.1,.02,1.03],eth:[17,41.2,.60,2.02],rules:[40,.50,30,30,0,.50,3]}
];
const variants = [
  {id:21,btc:[13,38.5,.47,1.76],eth:[14,50.0,.96,2.92],rules:[60,.75,30,30,0,.50,3]},
  {id:20,btc:[13,30.8,.15,1.22],eth:[14,50.0,.95,2.91],rules:[60,.75,30,30,0,.10,3]},
  {id:29,btc:[9,33.3,.28,1.42],eth:[13,53.8,1.11,3.40],rules:[60,.75,50,30,0,.50,3]}
];
const reports=[
 {id:'daily-support-bounce',date:'2026-08-03',name:{ko:'일봉 지지선 강세 캔들',en:'Daily Support Bullish Candle'},desc:{ko:'기존 BTC/ETH 일봉 지지선 반등 연구',en:'Original BTC/ETH daily support-bounce study.'},status:{ko:'공통 60% 승률 조건을 만족한 조합은 찾지 못했습니다.',en:'No common configuration met the 60% win-rate condition.'},configs:baseline,charts:['/charts/config-5016-btc-equity.png','/charts/config-5016-eth-equity.png'],captions:['BTCUSDT · 18 trades · +0.07R · PF 1.09','ETHUSDT · 11 trades · +0.42R · PF 1.66'],files:[['전략 README','Strategy README','/assets/daily-support-bounce/README.md'],['백테스트 엔진','Backtest engine','/assets/daily-support-bounce/btc_support_backtest.py'],['결과 요약','Result summary','/assets/daily-support-bounce/SUMMARY.md']]},
 {id:'daily-support-variants',date:'2026-08-03',name:{ko:'지지선 강세 캔들 · 스윕 회복 연구',en:'Support Bullish Candle · Sweep-Reclaim Study'},desc:{ko:'강한 종가·불리시 엔걸핑·지지선 하향 스윕 후 회복을 2024+ 보류 구간에서 비교했습니다.',en:'Compared strong-close, bullish-engulfing, and sweep-reclaim variants on the 2024+ holdout.'},status:{ko:'최선 균형 후보: 지지선 하향 스윕 후 회복 #21. BTC 38.5%, ETH 50.0% 승률로 60% 목표는 미달입니다.',en:'Best balanced candidate: sweep reclaim #21. BTC 38.5% and ETH 50.0% win rates do not meet the 60% target.'},configs:variants,charts:['/charts/support-variants-sweep-21-btc.png','/charts/support-variants-sweep-21-eth.png'],captions:['BTCUSDT · 13 trades · +0.47R · PF 1.76','ETHUSDT · 14 trades · +0.96R · PF 2.92'],files:[['연구 요약','Research summary','/assets/daily-support-variants-2026-08-03/SUMMARY.md'],['변형 백테스트 코드','Variant backtest code','/assets/daily-support-variants-2026-08-03/research_support_variants.py'],['백테스트 엔진','Backtest engine','/assets/daily-support-variants-2026-08-03/btc_support_backtest.py'],['설정 그리드','Configuration grid','/assets/daily-support-variants-2026-08-03/config_grid.csv'],['개발 구간 성과','Development metrics','/assets/daily-support-variants-2026-08-03/development_metrics.csv'],['보류 구간 성과','Holdout metrics','/assets/daily-support-variants-2026-08-03/holdout_metrics.csv'],['#21 BTC 거래','#21 BTC trades','/assets/daily-support-variants-2026-08-03/sweep_reclaim_21_btc_trades.csv'],['#21 ETH 거래','#21 ETH trades','/assets/daily-support-variants-2026-08-03/sweep_reclaim_21_eth_trades.csv']]}
];
let lang='ko', selectedReport='daily-support-variants', selectedId=21;
const text={ko:{reports:'리포트 선택',rules:'선택한 조합 규칙',perf:'후보 조합 성과',files:'전략 파일',copy:'텍스트 복사',loading:'파일을 불러오는 중…',support:'지지선',touch:'터치 범위',body:'몸통 비율',close:'종가 위치',trend:'추세 필터',stop:'손절 버퍼',target:'익절 목표',none:'없음',result:'검증 결과'},en:{reports:'Select report',rules:'Selected configuration rules',perf:'Candidate performance',files:'Strategy files',copy:'Copy text',loading:'Loading file…',support:'Support age',touch:'Touch band',body:'Body ratio',close:'Close location',trend:'Trend filter',stop:'Stop buffer',target:'Profit target',none:'None',result:'Validation result'}};
function rules(r,t){return [[t.support,`${r[0]} bars (3-left / 3-right swing low)`],[t.touch,`±${r[1].toFixed(2)}%`],[t.body,`≥ ${r[2]}% of range`],[t.close,`Top ${r[3]}%`],[t.trend,r[4]?`Close > SMA ${r[4]}`:t.none],[t.stop,`${r[5].toFixed(2)}% below signal low`],[t.target,`${r[6].toFixed(1)}R`]].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
function render(){const t=text[lang],r=reports.find(x=>x.id===selectedReport); const rows=r.configs.map(c=>`<tr><td><button class="config-select" data-id="${c.id}">#${c.id}</button></td><td>${c.btc[0]} / ${c.eth[0]}</td><td>${c.btc[1]}% / ${c.eth[1]}%</td><td>+${c.btc[2].toFixed(2)}R / +${c.eth[2].toFixed(2)}R</td><td>${c.btc[3].toFixed(2)} / ${c.eth[3].toFixed(2)}</td></tr>${selectedId===c.id?`<tr class="config-detail-row"><td colspan="5"><div class="config-grid">${rules(c.rules,t)}</div></td></tr>`:''}`).join('');
document.querySelector('#app').innerHTML=`<div class="wrap"><nav><span class="brand">BT LAB<span>BACKTEST RESEARCH</span></span><div class="nav-controls"><label class="report-control">${t.reports}<select id="report">${reports.map(x=>`<option value="${x.id}" ${x.id===r.id?'selected':''}>${x.name[lang]} · ${x.date}</option>`).join('')}</select></label><div id="language-toggle"><button data-lang="ko" class="${lang==='ko'?'active':''}">KR</button><button data-lang="en" class="${lang==='en'?'active':''}">EN</button></div></div></nav><p class="eyebrow">BTCUSDT / ETHUSDT · Daily <span class="date-chip">${r.date}</span></p><h1>${r.name[lang]}</h1><p class="sub">${r.desc[lang]}</p><div class="banner"><b>${t.result}</b> ${r.status[lang]}</div><section><h2>${t.rules}: #${selectedId}</h2><div class="rules">${rules(r.configs.find(c=>c.id===selectedId).rules,t)}</div></section><section><h2>Equity curves</h2><div class="charts">${r.charts.map((p,i)=>`<figure><img src="${p}" alt="equity curve"/><figcaption>${r.captions[i]}</figcaption></figure>`).join('')}</div></section><section><h2>${t.perf}</h2><div class="table-wrap"><table><thead><tr><th>Config</th><th>Trades<br>BTC / ETH</th><th>Win rate<br>BTC / ETH</th><th>Expectancy R<br>BTC / ETH</th><th>PF<br>BTC / ETH</th></tr></thead><tbody>${rows}</tbody></table></div></section><section><h2>${t.files}</h2><div class="file-layout"><div class="file-list">${r.files.map(([ko,en,p])=>`<button class="file-select" data-path="${p}">${lang==='ko'?ko:en}</button>`).join('')}</div><div class="file-viewer"><div class="file-toolbar"><b id="file-name"></b><button id="copy-file">${t.copy}</button></div><pre id="file-content">${t.loading}</pre></div></div></section></div>`;
document.querySelector('#report').onchange=e=>{selectedReport=e.target.value;selectedId=reports.find(x=>x.id===selectedReport).configs[0].id;render()};document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;render()});document.querySelectorAll('.config-select').forEach(b=>b.onclick=()=>{selectedId=+b.dataset.id;render()});const load=async b=>{document.querySelector('#file-name').textContent=b.textContent;const out=document.querySelector('#file-content');out.textContent=t.loading;try{const q=await fetch(b.dataset.path);out.textContent=q.ok?await q.text():'Could not load file.'}catch{out.textContent='Could not load file.'}};document.querySelectorAll('.file-select').forEach(b=>b.onclick=()=>load(b));document.querySelector('#copy-file').onclick=()=>navigator.clipboard?.writeText(document.querySelector('#file-content').textContent);load(document.querySelector('.file-select'));}
render();
